### ISSUE TITLE
PHP Fatal error:  Class 'PHPUnit_Framework_MockObject_Generator' not found

### ISSUE THREAD

**Issue by Pepelac** [arron0/testit#1]
Doesn't  work with PHPUnit 6.5.14.

PHP Fatal error:  Class 'PHPUnit_Framework_MockObject_Generator' not found in /var/www/html/vendor/arron/testit/TestIt/Tools/MockGenerator.php on line 26

PHPUnit 6.5 requires phpunit/phpunit-mock-objects: ^5.0 where Generator class has been moved to own namespace 

https://github.com/arron0/testit/blob/a93974c6eafa20c2e9e50be5706641ef53cc7192/TestIt/Tools/MockGenerator.php#L26

**Comment by arron0** [comment]
Use v5.* Version 4.* compatibility is limited to PHPUnit <6.5
